### PR TITLE
Automatic detection of resource folder location

### PR DESCRIPTION
**Pull request by lpn**

### CODE REVIEW

**Comment by Zamiell** [comment]
Did you even test this? It fails on my machine (Windows 7).

**Comment by lpn** [comment]
Yes, worked fine from cmdline and explorer. Win7/x64.
Could you provide details regarding where it fails?

**Comment by Zamiell** [comment]
Upon running it: `/steam\SteamApps\common\The was unexpected at this time.`

**Comment by lpn** [comment]
This is strange, I tested it on both default and custom install locations.
What does running 'cmd /k reg query "HKCU\Software\Valve\Steam" /V SteamPath' return on your system?

**Comment by Zamiell** [comment]
It returns this:

```
HKEY_CURRENT_USER\Software\Valve\Steam
    SteamPath    REG_SZ    c:/program files (x86)/steam
```

**Pull request merged**
